dns_managed_zone: cdn2954732

proxy_subnet_cidrs:
  europe-west4: 10.0.0.0/24

router_asn: 64514

balancers:
  balancer4:
    region: europe-west4
    backend_ip: 212.118.36.11
    backend_port: 444
    frontend_port: 443
  balancer5:
    region: europe-west4
    backend_ip: 212.118.36.11
    backend_port: 445
    frontend_port: 443
